from time import time
import torch
from mapping import *
from dataloader.dataloader import *
from dataloader.mysql_dataloader import *
from model.imdb_model import IMDBModel

from minlptokenizer.tokenizer import MiNLPTokenizer


def test_dataloader():
    test_dataloader = Dataloader(['dataset/test.txt'], 10, False)
    test_dataloader.reset()
    for i in range(100000):
        print(test_dataloader.next())


batch_size = 100
mapping_size = 3000
max_word_size = 100


def test_mapping():
    train_dataloader = Dataloader(['dataset/train.txt'], batch_size)
    train_dataloader.reset()
    data = train_dataloader.next()
    mp = mapping(max_word_size)
    # mp = mapping.load('dump/mapping_3000.data')
    # print(data['input'])
    # print(mp.mapping_from_sentences(data['input']))
    # print(mp.get_sentences(mp.mapping_from_sentences(data['input'])))

    # return
    while data:
        mp.add_sentences(data.get('input'))
        data = train_dataloader.next()
    mp.init(mapping_size)
    train_dataloader.reset()
    data = train_dataloader.next()
    mp.dump('dump/mapping_3000.data')
    # mp=mapping.load('dump/mapping_2000.data')
    # print(mp.mapping_from_sentences(data['input']).cuda())
    # print(mp.get_idx())
    # print(mp.get_frequency())


def test_tokenizer():
    # train_dataloader = mysql_dataloader(10,shuffle=False)
    # train_dataloader.reset()
    tokenizer = MiNLPTokenizer(granularity='fine')  # fine：细粒度，coarse：粗粒度，默认为细粒度
    train_dataloader = Dataloader(['dataset/train.txt'], batch_size)
    train_dataloader.reset()
    data = train_dataloader.next()
    mp = mapping(max_word_size)
    # mp = mapping.load('dump/tokenizer_mapping_3000.data')
    # print(mp.mapping_from_sentence(tokenizer.cut('我觉得你是傻子')))
    # print(mp.mapping_from_sentence(tokenizer.cut('他跟我也觉得你不是是傻子')))
    # print(mp.get_idx())
    while data:
        mp.add_sentences(tokenizer.cut(data.get('input')))
        data = train_dataloader.next()
    mp.init(mapping_size)
    mp.dump('dump/tokenizer_mapping_3000.data')
    # print(mp.get_idx())
    # print(mp.get_frequency())

    # while data:
    #     print(data['input'])
    #     print(tokenizer.cut(data['input']))
    #     data=train_dataloader.next()
    #     break
    # print(tokenizer.cut('今天天气怎么样？'))


def test_model():
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    from torch import optim

    # mp = mapping.load('dump/mapping_3000.data')
    mp = mapping.load('dump/tokenizer_mapping_3000.data')
    mp.set_word_size(max_word_size)
    vocab_size = mp.mapping_size
    device = 'cuda:0'
    device = 'cpu'
    imdb_model = IMDBModel(vocab_size, max_word_size).to(device)
    # print(list(imdb_model.parameters()))
    optimizer = optim.Adam(imdb_model.parameters())
    criterion = nn.CrossEntropyLoss()
    tokenizer = MiNLPTokenizer(granularity='fine')
    # print(imdb_model)

    train_dataloader = Dataloader(['dataset/train.txt'], batch_size)
    test_dataloader = Dataloader(['dataset/test.txt'], batch_size)
    inference_dataloader = mysql_dataloader(batch_size)

    def train(epoch):
        imdb_model.train()
        step = 0
        train_dataloader.reset()
        data = train_dataloader.next()
        while data:
            optimizer.zero_grad()
            input = mp.mapping_from_sentences(tokenizer.cut(data['input'])).to(device)
            output = imdb_model(input).to(device)
            target = torch.tensor(data['label']).to(device)
            # target = F.one_hot(torch.tensor(target), num_classes=2)
            # print(output.shape,target.shape)
            loss = F.nll_loss(output, target)  # traget需要是[0,9]，不能是[1-10]
            loss.backward()
            # print("loss",loss)
            optimizer.step()
            if step % 10 == 0:
                print('Train Epoch: {} [{})]\tLoss: {:.6f}'.format(epoch, step, loss.item()))
            step += 1
            data = train_dataloader.next()

    def test():
        test_loss = 0
        correct = 0
        total = 0
        imdb_model.eval()
        test_dataloader.reset()
        data = test_dataloader.next()
        with torch.no_grad():
            while data:
                input = mp.mapping_from_sentences(tokenizer.cut(data['input'])).to(device)
                target = torch.tensor(data['label']).to(device)
                output = imdb_model(input).to(device)
                test_loss += F.nll_loss(output, target, reduction="sum")
                pred = torch.max(output, dim=-1, keepdim=False)[-1]
                correct += pred.eq(target.data).sum()
                total += target.shape[0]
                # print(correct,total)
                data = test_dataloader.next()
            test_loss = test_loss / total
            print(
                '\nTest set: Avg. loss: {:.4f}, Accuracy: {}/{} ({:.2f}%)\n'.format(
                    test_loss, correct, total, 100.0 * correct / total
                )
            )

    def inference():
        imdb_model.eval()
        inference_dataloader.reset()
        data = inference_dataloader.next()
        with torch.no_grad():
            while data:
                input = mp.mapping_from_sentences(tokenizer.cut(data['input'])).to(device)
                target = torch.tensor(data['label']).to(device)
                output = imdb_model(input).to(device)
                pred = torch.max(output, dim=-1, keepdim=False)[-1]
                res = list(zip(data['input'], pred))
                print('\n'.join([str(x) for x in res]))
                # print(correct,total)
                data = inference_dataloader.next()
                break

    # inference()
    # return
    test()
    for i in range(5):
        train(i)
        test()
        inference()
    # test()


if __name__ == '__main__':
    # print(torch.__version__)
    # print(torch.cuda.is_available())
    # test_mapping()
    # test_tokenizer()
    # test_model()
    a = {
        'cardlistInfo': {
            'containerid': '1076035319509655',
            'v_p': 42,
            'show_style': 1,
            'total': 715,
            'since_id': 4706017491550958,
        },
        'cards': [
            {
                'card_type': 11,
                'card_style': 1,
                'display_arrow': 0,
                'skip_group_title': True,
                'card_group': [
                    {
                        'card_type': 17,
                        'col': 1,
                        'group': [
                            {
                                'title_sub': '#实时号测试#',
                                'word_scheme': '#实时号测试#',
                                'scheme': 'https://m.weibo.cn/search?isnewpage=1&disable_history=1&disable_sug=1&extparam=c_type%3D99%26profile_uid%3D5319509655&luicode=10000011&lfid=1076035319509655&containerid=100103type%3D401%26t%3D99%26q%3D%23%E5%AE%9E%E6%97%B6%E5%8F%B7%E6%B5%8B%E8%AF%95%23',
                                'action_log': {
                                    'act_code': 3089,
                                    'oid': '5319509655',
                                    'ext': 'scene:profileMblog',
                                    'fid': '',
                                },
                            }
                        ],
                    }
                ],
            },
            {
                'card_type': 9,
                'itemid': '1076035319509655_-_4554984320405485',
                'scheme': 'https://m.weibo.cn/status/Jn4oo1Hu5?mblogid=Jn4oo1Hu5&luicode=10000011&lfid=1076035319509655',
                'mblog': {
                    'visible': {'type': 0, 'list_id': 0},
                    'created_at': 'Wed Sep 30 22:32:32 +0800 2020',
                    'id': '4554984320405485',
                    'mid': '4554984320405485',
                    'can_edit': False,
                    'show_additional_indication': 0,
                    'text': '10月很好，秋天也很好，<br />桂花会开，空气会香甜。<br />我们会变好，一切充满希望，温柔又热烈。<br />❤️🧡💛💚💙💜\U0001f90d ',
                    'textLength': 113,
                    'source': 'iPhone客户端',
                    'favorited': False,
                    'pic_ids': ['005O07sPly1gj91tf78jjj30y00qjnj7'],
                    'pic_types': '0',
                    'thumbnail_pic': 'https://wx2.sinaimg.cn/thumbnail/005O07sPly1gj91tf78jjj30y00qjnj7.jpg',
                    'bmiddle_pic': 'http://wx2.sinaimg.cn/bmiddle/005O07sPly1gj91tf78jjj30y00qjnj7.jpg',
                    'original_pic': 'https://wx2.sinaimg.cn/large/005O07sPly1gj91tf78jjj30y00qjnj7.jpg',
                    'is_paid': False,
                    'mblog_vip_type': 0,
                    'user': {
                        'id': 5319509655,
                        'screen_name': 'YINGSSssYY',
                        'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.0.751.751.180/005O07sPly8fxle1ardi6j30kv0kvab2.jpg?KID=imgbed,tva&Expires=1638719372&ssig=0nWfvQeIJS',
                        'profile_url': 'https://m.weibo.cn/u/5319509655?uid=5319509655&luicode=10000011&lfid=1076035319509655',
                        'statuses_count': 826,
                        'verified': True,
                        'verified_type': 0,
                        'verified_type_ext': 0,
                        'verified_reason': '微博原创视频博主',
                        'close_blue_v': False,
                        'description': 'If we can only encounter each other rather than stay with each other, then I wish we had never encountered.',
                        'gender': 'f',
                        'mbtype': 12,
                        'urank': 32,
                        'mbrank': 3,
                        'follow_me': False,
                        'following': False,
                        'follow_count': 67,
                        'followers_count': '1463',
                        'followers_count_str': '1463',
                        'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/005O07sPly1ghehzohj1kj30u00u0dim.jpg',
                        'avatar_hd': 'https://wx4.sinaimg.cn/orj480/005O07sPly8fxle1ardi6j30kv0kvab2.jpg',
                        'like': False,
                        'like_me': False,
                        'badge': {
                            'bind_taobao': 1,
                            'unread_pool': 1,
                            'unread_pool_ext': 1,
                            'dzwbqlx_2016': 1,
                            'league_badge': 1,
                            'travel_2017': 1,
                            'panda': 1,
                            'user_name_certificate': 1,
                            'hongbao_2020': 2,
                            'pc_new': 7,
                            'hongbaofeijika_2021': 1,
                            'party_cardid_state': 1,
                        },
                    },
                    'picStatus': '0:1',
                    'reposts_count': 0,
                    'comments_count': 0,
                    'reprint_cmt_count': 0,
                    'attitudes_count': 2,
                    'pending_approval_count': 0,
                    'isLongText': False,
                    'reward_exhibition_type': 0,
                    'hide_flag': 0,
                    'mlevel': 0,
                    'darwin_tags': [],
                    'mblogtype': 2,
                    'rid': '0_0_50_6665514537312526293_0_0_0',
                    'more_info_type': 0,
                    'extern_safe': 0,
                    'number_display_strategy': {
                        'apply_scenario_flag': 3,
                        'display_text_min_number': 1000000,
                        'display_text': '100万+',
                    },
                    'enable_comment_guide': True,
                    'content_auth': 0,
                    'pic_num': 1,
                    'alchemy_params': {'ug_red_envelope': False},
                    'reprint_type': 0,
                    'can_reprint': True,
                    'new_comment_style': 0,
                    'mblog_menu_new_style': 0,
                    'edit_config': {'edited': False},
                    'isTop': 1,
                    'pics': [
                        {
                            'pid': '005O07sPly1gj91tf78jjj30y00qjnj7',
                            'url': 'https://wx2.sinaimg.cn/orj360/005O07sPly1gj91tf78jjj30y00qjnj7.jpg',
                            'size': 'orj360',
                            'geo': {'width': 346, 'height': 270, 'croped': False},
                            'large': {
                                'size': 'large',
                                'url': 'https://wx2.sinaimg.cn/large/005O07sPly1gj91tf78jjj30y00qjnj7.jpg',
                                'geo': {'width': '1224', 'height': '955', 'croped': False},
                            },
                        }
                    ],
                    'title': {'text': '置顶', 'base_color': 1},
                    'bid': 'Jn4oo1Hu5',
                },
            },
            {
                'card_type': 9,
                'itemid': '1076035319509655_-_4711080239042331',
                'scheme': 'https://m.weibo.cn/status/L4EflBWk3?mblogid=L4EflBWk3&luicode=10000011&lfid=1076035319509655',
                'mblog': {
                    'visible': {'type': 0, 'list_id': 0},
                    'created_at': 'Sun Dec 05 16:21:59 +0800 2021',
                    'id': '4711080239042331',
                    'mid': '4711080239042331',
                    'can_edit': False,
                    'show_additional_indication': 0,
                    'text': '<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C%E7%AC%AC%E4%B8%89%E5%AD%A3%E6%94%B6%E5%AE%98%23&extparam=%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C%E7%AC%AC%E4%B8%89%E5%AD%A3%E6%94%B6%E5%AE%98%23&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#我们的歌第三季收官#</span></a> 牛奶小胡子<span class="url-icon"><img alt=[haha] src="https://h5.sinaimg.cn/m/emoticon/icon/others/h_haha-dd41b13682.png" style="width:1em; height:1em;" /></span><span class="url-icon"><img alt=[haha] src="https://h5.sinaimg.cn/m/emoticon/icon/others/h_haha-dd41b13682.png" style="width:1em; height:1em;" /></span><span class="url-icon"><img alt=[haha] src="https://h5.sinaimg.cn/m/emoticon/icon/others/h_haha-dd41b13682.png" style="width:1em; height:1em;" /></span>',
                    'source': '微博国际版',
                    'favorited': False,
                    'pic_ids': [],
                    'pic_types': '',
                    'is_paid': False,
                    'mblog_vip_type': 0,
                    'user': {
                        'id': 5319509655,
                        'screen_name': 'YINGSSssYY',
                        'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.0.751.751.180/005O07sPly8fxle1ardi6j30kv0kvab2.jpg?KID=imgbed,tva&Expires=1638719372&ssig=0nWfvQeIJS',
                        'profile_url': 'https://m.weibo.cn/u/5319509655?uid=5319509655&luicode=10000011&lfid=1076035319509655',
                        'statuses_count': 826,
                        'verified': True,
                        'verified_type': 0,
                        'verified_type_ext': 0,
                        'verified_reason': '微博原创视频博主',
                        'close_blue_v': False,
                        'description': 'If we can only encounter each other rather than stay with each other, then I wish we had never encountered.',
                        'gender': 'f',
                        'mbtype': 12,
                        'urank': 32,
                        'mbrank': 3,
                        'follow_me': False,
                        'following': False,
                        'follow_count': 67,
                        'followers_count': '1463',
                        'followers_count_str': '1463',
                        'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/005O07sPly1ghehzohj1kj30u00u0dim.jpg',
                        'avatar_hd': 'https://wx4.sinaimg.cn/orj480/005O07sPly8fxle1ardi6j30kv0kvab2.jpg',
                        'like': False,
                        'like_me': False,
                        'badge': {
                            'bind_taobao': 1,
                            'unread_pool': 1,
                            'unread_pool_ext': 1,
                            'dzwbqlx_2016': 1,
                            'league_badge': 1,
                            'travel_2017': 1,
                            'panda': 1,
                            'user_name_certificate': 1,
                            'hongbao_2020': 2,
                            'pc_new': 7,
                            'hongbaofeijika_2021': 1,
                            'party_cardid_state': 1,
                        },
                    },
                    'retweeted_status': {
                        'visible': {'type': 0, 'list_id': 0},
                        'created_at': 'Sun Dec 05 11:00:03 +0800 2021',
                        'id': '4710999226318959',
                        'mid': '4710999226318959',
                        'can_edit': False,
                        'show_additional_indication': 0,
                        'text': '<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C%E7%AC%AC%E4%B8%89%E5%AD%A3%E6%94%B6%E5%AE%98%23&extparam=%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C%E7%AC%AC%E4%B8%89%E5%AD%A3%E6%94%B6%E5%AE%98%23&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#我们的歌第三季收官#</span></a><a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C%23&isnewpage=1&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#我们的歌#</span></a>经典的歌曲永不过时，热爱音乐的“牛奶小胡子”<a href=\'/n/林子祥LAMUSICAL\'>@林子祥LAMUSICAL</a>\xa0\xa0\xa0\xa0\xa0<a href=\'/n/胡夏\'>@胡夏</a>\xa0\xa0 永远年轻。今晚21:03  ，锁定东方卫视<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C3%23&extparam=%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C3%23&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#我们的歌3#</span></a>\xa0，和他们一起嗨唱青春样！ ',
                        'textLength': 174,
                        'source': '微博 weibo.com',
                        'favorited': False,
                        'pic_ids': ['bf6aedbcgy1gx20vo714mj20u01hd7fi'],
                        'pic_types': '',
                        'thumbnail_pic': 'https://wx1.sinaimg.cn/thumbnail/bf6aedbcgy1gx20vo714mj20u01hd7fi.jpg',
                        'bmiddle_pic': 'http://wx1.sinaimg.cn/bmiddle/bf6aedbcgy1gx20vo714mj20u01hd7fi.jpg',
                        'original_pic': 'https://wx1.sinaimg.cn/large/bf6aedbcgy1gx20vo714mj20u01hd7fi.jpg',
                        'is_paid': False,
                        'mblog_vip_type': 0,
                        'user': {
                            'id': 3211455932,
                            'screen_name': '东方卫视我们的歌',
                            'profile_image_url': 'https://tvax1.sinaimg.cn/crop.0.0.1080.1080.180/003vkWokly8gtzru8u27fj60u00u0jv502.jpg?KID=imgbed,tva&Expires=1638719372&ssig=YJA7JkVVf5',
                            'profile_url': 'https://m.weibo.cn/u/3211455932?uid=3211455932&luicode=10000011&lfid=1076035319509655',
                            'statuses_count': 14464,
                            'verified': True,
                            'verified_type': 3,
                            'verified_type_ext': 0,
                            'verified_reason': '东方卫视《我们的歌》官方微博',
                            'close_blue_v': False,
                            'description': '东方卫视代际潮音竞演节目',
                            'gender': 'm',
                            'mbtype': 11,
                            'urank': 37,
                            'mbrank': 6,
                            'follow_me': False,
                            'following': False,
                            'follow_count': 618,
                            'followers_count': '189.8万',
                            'followers_count_str': '189.8万',
                            'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/003vkWokly1gtzqx733afj60wi0wijuq02.jpg',
                            'avatar_hd': 'https://wx1.sinaimg.cn/orj480/003vkWokly8gtzru8u27fj60u00u0jv502.jpg',
                            'like': False,
                            'like_me': False,
                            'badge': {
                                'bind_taobao': 1,
                                'zongyiji': 1,
                                'follow_whitelist_video': 1,
                                'user_name_certificate': 1,
                                'hongbao_2020': 2,
                                'feiyan_2020': 1,
                                'pc_new': 6,
                                'weibozhiye_2020': 1,
                                'yuanlongping_2021': 1,
                            },
                        },
                        'reposts_count': 106,
                        'comments_count': 218,
                        'reprint_cmt_count': 0,
                        'attitudes_count': 702,
                        'pending_approval_count': 0,
                        'isLongText': False,
                        'reward_exhibition_type': 0,
                        'hide_flag': 0,
                        'mlevel': 0,
                        'darwin_tags': [],
                        'mblogtype': 0,
                        'rid': '1_0_50_6665514537312526293_0_0_0',
                        'more_info_type': 0,
                        'content_auth': 0,
                        'pic_num': 1,
                        'reprint_type': 0,
                        'can_reprint': True,
                        'new_comment_style': 0,
                        'edit_config': {'edited': False},
                        'page_info': {
                            'type': 'search_topic',
                            'object_type': 0,
                            'page_pic': {
                                'url': 'https://wx1.sinaimg.cn/large/bf6aedbcly8gx2qaoshfdj20u00u0gq0.jpg'
                            },
                            'page_url': 'https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C%E7%AC%AC%E4%B8%89%E5%AD%A3%E6%94%B6%E5%AE%98%23&extparam=%23%E6%88%91%E4%BB%AC%E7%9A%84%E6%AD%8C%E7%AC%AC%E4%B8%89%E5%AD%A3%E6%94%B6%E5%AE%98%23&luicode=10000011&lfid=1076035319509655',
                            'page_title': '#我们的歌第三季收官#',
                            'content1': '0讨论 0阅读 ',
                        },
                        'pics': [
                            {
                                'pid': 'bf6aedbcgy1gx20vo714mj20u01hd7fi',
                                'url': 'https://wx1.sinaimg.cn/orj360/bf6aedbcgy1gx20vo714mj20u01hd7fi.jpg',
                                'size': 'orj360',
                                'geo': {'width': 360, 'height': 640, 'croped': False},
                                'large': {
                                    'size': 'large',
                                    'url': 'https://wx1.sinaimg.cn/large/bf6aedbcgy1gx20vo714mj20u01hd7fi.jpg',
                                    'geo': {'width': '1080', 'height': '1921', 'croped': False},
                                },
                            }
                        ],
                        'bid': 'L4C8GqvQH',
                    },
                    'reposts_count': 0,
                    'comments_count': 0,
                    'reprint_cmt_count': 0,
                    'attitudes_count': 0,
                    'pending_approval_count': 0,
                    'isLongText': False,
                    'reward_exhibition_type': 0,
                    'hide_flag': 0,
                    'mlevel': 0,
                    'darwin_tags': [],
                    'mblogtype': 0,
                    'rid': '1_0_50_6665514537312526293_0_0_0',
                    'more_info_type': 0,
                    'cardid': 'star_033',
                    'extern_safe': 0,
                    'number_display_strategy': {
                        'apply_scenario_flag': 3,
                        'display_text_min_number': 1000000,
                        'display_text': '100万+',
                    },
                    'enable_comment_guide': True,
                    'content_auth': 0,
                    'repost_type': 3,
                    'pic_num': 0,
                    'alchemy_params': {'ug_red_envelope': False},
                    'reprint_type': 0,
                    'can_reprint': False,
                    'new_comment_style': 0,
                    'mblog_menu_new_style': 0,
                    'edit_config': {'edited': False},
                    'raw_text': '#我们的歌第三季收官# 牛奶小胡子[haha][haha][haha]',
                    'bid': 'L4EflBWk3',
                },
                'lastWeiboCard': True,
            },
            {
                'card_type': 9,
                'itemid': '1076035319509655_-_4709621442545993',
                'scheme': 'https://m.weibo.cn/status/L42isaGkp?mblogid=L42isaGkp&luicode=10000011&lfid=1076035319509655',
                'mblog': {
                    'visible': {'type': 0, 'list_id': 0},
                    'created_at': 'Wed Dec 01 15:45:15 +0800 2021',
                    'id': '4709621442545993',
                    'mid': '4709621442545993',
                    'can_edit': False,
                    'version': 1,
                    'show_additional_indication': 0,
                    'text': '<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E7%8E%8B%E8%8E%89%E8%83%A1%E5%A4%8F%E5%94%B1%E7%81%AF%E7%81%AB%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%23&extparam=%23%E7%8E%8B%E8%8E%89%E8%83%A1%E5%A4%8F%E5%94%B1%E7%81%AF%E7%81%AB%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%23&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#王莉胡夏唱灯火里的中国#</span></a> “灯火漫卷的万里山河，初心换回了百年承诺”//<a href=\'/n/胡夏\'>@胡夏</a>:<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E7%8E%8B%E8%8E%89%E8%83%A1%E5%A4%8F%E5%94%B1%E7%81%AF%E7%81%AB%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%23&extparam=%23%E7%8E%8B%E8%8E%89%E8%83%A1%E5%A4%8F%E5%94%B1%E7%81%AF%E7%81%AB%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%23&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#王莉胡夏唱灯火里的中国#</span></a> 万里锦绣河山，万家灯火璀璨。很荣幸和王莉老师<a href=\'/n/王莉美声\'>@王莉美声</a> 一起演绎这首歌曲，祝福祖国国泰民安，繁荣昌盛！<span class="url-icon"><img alt=[心] src="https://h5.sinaimg.cn/m/emoticon/icon/others/l_xin-43af9086c0.png" style="width:1em; height:1em;" /></span>',
                    'source': '',
                    'favorited': False,
                    'pic_ids': [],
                    'pic_types': '',
                    'is_paid': False,
                    'mblog_vip_type': 0,
                    'user': {
                        'id': 5319509655,
                        'screen_name': 'YINGSSssYY',
                        'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.0.751.751.180/005O07sPly8fxle1ardi6j30kv0kvab2.jpg?KID=imgbed,tva&Expires=1638719372&ssig=0nWfvQeIJS',
                        'profile_url': 'https://m.weibo.cn/u/5319509655?uid=5319509655&luicode=10000011&lfid=1076035319509655',
                        'statuses_count': 826,
                        'verified': True,
                        'verified_type': 0,
                        'verified_type_ext': 0,
                        'verified_reason': '微博原创视频博主',
                        'close_blue_v': False,
                        'description': 'If we can only encounter each other rather than stay with each other, then I wish we had never encountered.',
                        'gender': 'f',
                        'mbtype': 12,
                        'urank': 32,
                        'mbrank': 3,
                        'follow_me': False,
                        'following': False,
                        'follow_count': 67,
                        'followers_count': '1463',
                        'followers_count_str': '1463',
                        'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/005O07sPly1ghehzohj1kj30u00u0dim.jpg',
                        'avatar_hd': 'https://wx4.sinaimg.cn/orj480/005O07sPly8fxle1ardi6j30kv0kvab2.jpg',
                        'like': False,
                        'like_me': False,
                        'badge': {
                            'bind_taobao': 1,
                            'unread_pool': 1,
                            'unread_pool_ext': 1,
                            'dzwbqlx_2016': 1,
                            'league_badge': 1,
                            'travel_2017': 1,
                            'panda': 1,
                            'user_name_certificate': 1,
                            'hongbao_2020': 2,
                            'pc_new': 7,
                            'hongbaofeijika_2021': 1,
                            'party_cardid_state': 1,
                        },
                    },
                    'pid': 4709598433117909,
                    'pidstr': '4709598433117909',
                    'retweeted_status': {
                        'visible': {'type': 0, 'list_id': 0},
                        'created_at': 'Wed Dec 01 12:41:44 +0800 2021',
                        'id': '4709575260114966',
                        'mid': '4709575260114966',
                        'edit_count': 1,
                        'can_edit': False,
                        'edit_at': 'Wed Dec 01 12:53:59 +0800 2021',
                        'version': 3,
                        'show_additional_indication': 0,
                        'text': '<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E7%8E%8B%E8%8E%89%E8%83%A1%E5%A4%8F%E5%94%B1%E7%81%AF%E7%81%AB%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%23&extparam=%23%E7%8E%8B%E8%8E%89%E8%83%A1%E5%A4%8F%E5%94%B1%E7%81%AF%E7%81%AB%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%23&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#王莉胡夏唱灯火里的中国#</span></a> <a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E7%8C%AE%E7%A4%BC%E9%9F%B3%E4%B9%90%E4%B8%93%E8%BE%91%E7%99%BE%E5%B9%B4%23&extparam=%23%E7%8C%AE%E7%A4%BC%E9%9F%B3%E4%B9%90%E4%B8%93%E8%BE%91%E7%99%BE%E5%B9%B4%23&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#献礼音乐专辑百年#</span></a>系列作品之《灯火里的中国》MV正式发布，由<a href=\'/n/王莉美声\'>@王莉美声</a> 和<a href=\'/n/胡夏\'>@胡夏</a> 共同演绎，带你眺望溶溶月色中的万家灯火。  <a data-url="http://t.cn/A6x9vk0K" href="https://video.weibo.com/show?fid=1034:4709570413789261" data-hide=""><span class=\'url-icon\'><img style=\'width: 1rem;height: 1rem\' src=\'https://h5.sinaimg.cn/upload/2015/09/25/3/timeline_card_small_video_default.png\'></span><span class="surl-text">新浪音乐的微博视频</span></a> ',
                        'textLength': 163,
                        'source': '微博视频号',
                        'favorited': False,
                        'pic_ids': [],
                        'pic_types': '',
                        'is_paid': False,
                        'mblog_vip_type': 0,
                        'user': {
                            'id': 1266269835,
                            'screen_name': '新浪音乐',
                            'profile_image_url': 'https://tvax3.sinaimg.cn/crop.0.0.1080.1080.180/001nH8D1ly8gln4iamgfbj60u00u0jsy02.jpg?KID=imgbed,tva&Expires=1638719372&ssig=Z1ownSjDIS',
                            'profile_url': 'https://m.weibo.cn/u/1266269835?uid=1266269835&luicode=10000011&lfid=1076035319509655',
                            'statuses_count': 37224,
                            'verified': True,
                            'verified_type': 7,
                            'verified_type_ext': 0,
                            'verified_reason': '新浪音乐频道官方微博',
                            'close_blue_v': False,
                            'description': '音乐是一种生活态度。新歌首发、演出推荐、歌手动态。',
                            'gender': 'm',
                            'mbtype': 12,
                            'urank': 48,
                            'mbrank': 6,
                            'follow_me': False,
                            'following': False,
                            'follow_count': 1069,
                            'followers_count': '747.5万',
                            'followers_count_str': '747.5万',
                            'cover_image_phone': 'https://tva1.sinaimg.cn/crop.0.0.640.640.640/549d0121tw1egm1kjly3jj20hs0hsq4f.jpg',
                            'avatar_hd': 'https://wx3.sinaimg.cn/orj480/001nH8D1ly8gln4iamgfbj60u00u0jsy02.jpg',
                            'like': False,
                            'like_me': False,
                            'badge': {
                                'zongyiji': 1,
                                'dzwbqlx_2016': 1,
                                'follow_whitelist_video': 1,
                                'user_name_certificate': 1,
                                'suishoupai_2018': 1,
                                'wenchuan_10th': 1,
                                'dailv_2018': 4,
                                'qixi_2018': 1,
                                'meilizhongguo_2018': 1,
                                'weibo_display_fans': 1,
                                'relation_display': 1,
                                'wbzy_2018': 1,
                                'memorial_2018': 1,
                                'suishoupai_2019': 1,
                                'wusi_2019': 1,
                                'hongrenjie_2019': 1,
                                'rrgyj_2019': 1,
                                'weishi_2019': 1,
                                'wbzy_2019': 1,
                                'feiyan_2020': 1,
                                'hope_2020': 1,
                                'kangyi_2020': 1,
                                'pc_new': 6,
                                'movie_2020': 1,
                                'weibozhiye_2020': 1,
                                'hongbaofeifuniu_2021': 1,
                                'weibozhiyexianxia_2021': 1,
                                'ylpshuidao_2021': 1,
                                'gaokao_2021': 1,
                                'party_cardid_state': 2,
                                'aoyun_2021': 1,
                                'kaixue21_2021': 1,
                                'yinyuejie21_2021': 1,
                            },
                        },
                        'reposts_count': 12914,
                        'comments_count': 239,
                        'reprint_cmt_count': 0,
                        'attitudes_count': 1478,
                        'pending_approval_count': 0,
                        'isLongText': False,
                        'reward_exhibition_type': 0,
                        'hide_flag': 0,
                        'mlevel': 0,
                        'darwin_tags': [],
                        'mblogtype': 0,
                        'rid': '2_0_50_6665514537312526293_0_0_0',
                        'more_info_type': 0,
                        'cardid': 'star_1377',
                        'content_auth': 0,
                        'safe_tags': 528384,
                        'pic_num': 0,
                        'fid': 4709574513787001,
                        'reprint_type': 0,
                        'can_reprint': True,
                        'new_comment_style': 0,
                        'edit_config': {
                            'edited': True,
                            'menu_edit_history': {
                                'scheme': 'sinaweibo://cardlist?containerid=231440_-_4709575260114966&title=编辑记录',
                                'title': '查看编辑记录',
                            },
                        },
                        'page_info': {
                            'type': 'video',
                            'object_type': 11,
                            'url_ori': 'http://t.cn/A6x9vk0K',
                            'page_pic': {
                                'width': 3838,
                                'pid': '001nH8D1ly1gwy7tm3rz2j61hb0u04em02',
                                'source': 1,
                                'is_self_cover': 1,
                                'type': 1,
                                'url': 'https://wx4.sinaimg.cn/crop.0.6.1919.1067/001nH8D1ly1gwy7tm3rz2j61hb0u04em02.jpg',
                                'height': 2134,
                            },
                            'page_url': 'https://video.weibo.com/show?fid=1034%3A4709570413789261&luicode=10000011&lfid=1076035319509655',
                            'object_id': '1034:4709570413789261',
                            'page_title': '新浪音乐的微博视频',
                            'title': '王莉胡夏唱《灯火里的中国》',
                            'content1': '新浪音乐的微博视频',
                            'content2': '#王莉胡夏唱灯火里的中国# 为庆祝中国共产党成立100周年，#献礼音乐专辑百年#系列作品之《灯火里的中国》MV正式发布，由@王莉美声 和@胡夏 共同演绎，带你眺望溶溶月色中的万家灯火。',
                            'video_orientation': 'horizontal',
                            'play_count': '125万次播放',
                            'media_info': {
                                'stream_url': 'https://f.video.weibocdn.com/o0/7gAUfErflx07ROTKvcsw01041200XLTR0E010.mp4?label=mp4_ld&template=640x360.25.0&trans_finger=6006a648d0db83b7d9951b3cee381a9c&ori=0&ps=1CwnkDw1GXwCQx&Expires=1638712172&ssig=%2FdVHPfHqP8&KID=unistore,video',
                                'stream_url_hd': 'https://f.video.weibocdn.com/o0/VeVuBxmdlx07ROTL2qI801041201yKxR0E010.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=d8257cc71422c9ad30fe69ce9523c87b&ori=0&ps=1CwnkDw1GXwCQx&Expires=1638712172&ssig=GRBtKpo4Dv&KID=unistore,video',
                                'duration': 261.826,
                            },
                            'urls': {
                                'mp4_720p_mp4': 'https://f.video.weibocdn.com/o0/0l2PHk9nlx07ROTMuIoU010412034EK30E020.mp4?label=mp4_720p&template=1280x720.25.0&trans_finger=775cb0ab963a74099cf9f840cd1987f1&ori=0&ps=1CwnkDw1GXwCQx&Expires=1638712172&ssig=fYpHesh3E%2B&KID=unistore,video',
                                'mp4_ld_mp4': 'https://f.video.weibocdn.com/o0/7gAUfErflx07ROTKvcsw01041200XLTR0E010.mp4?label=mp4_ld&template=640x360.25.0&trans_finger=6006a648d0db83b7d9951b3cee381a9c&ori=0&ps=1CwnkDw1GXwCQx&Expires=1638712172&ssig=%2FdVHPfHqP8&KID=unistore,video',
                                'mp4_hd_mp4': 'https://f.video.weibocdn.com/o0/VeVuBxmdlx07ROTL2qI801041201yKxR0E010.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=d8257cc71422c9ad30fe69ce9523c87b&ori=0&ps=1CwnkDw1GXwCQx&Expires=1638712172&ssig=GRBtKpo4Dv&KID=unistore,video',
                            },
                        },
                        'bid': 'L415Y0tUi',
                    },
                    'reposts_count': 0,
                    'comments_count': 0,
                    'reprint_cmt_count': 0,
                    'attitudes_count': 0,
                    'pending_approval_count': 0,
                    'isLongText': False,
                    'reward_exhibition_type': 0,
                    'hide_flag': 0,
                    'mlevel': 0,
                    'darwin_tags': [],
                    'mblogtype': 0,
                    'rid': '2_0_50_6665514537312526293_0_0_0',
                    'more_info_type': 0,
                    'cardid': 'star_033',
                    'extern_safe': 0,
                    'number_display_strategy': {
                        'apply_scenario_flag': 3,
                        'display_text_min_number': 1000000,
                        'display_text': '100万+',
                    },
                    'enable_comment_guide': True,
                    'content_auth': 0,
                    'safe_tags': 4096,
                    'repost_type': 3,
                    'pic_num': 0,
                    'alchemy_params': {'ug_red_envelope': False},
                    'reprint_type': 0,
                    'can_reprint': False,
                    'new_comment_style': 0,
                    'mblog_menu_new_style': 0,
                    'edit_config': {'edited': False},
                    'raw_text': '#王莉胡夏唱灯火里的中国# “灯火漫卷的万里山河，初心换回了百年承诺”//@胡夏:#王莉胡夏唱灯火里的中国# 万里锦绣河山，万家灯火璀璨。很荣幸和王莉老师@王莉美声 一起演绎这首歌曲，祝福祖国国泰民安，繁荣昌盛！[心]',
                    'bid': 'L42isaGkp',
                },
            },
            {
                'card_style': 1,
                'card_type': 11,
                'itemid': 'INTEREST_PEOPLE',
                'card_group': [
                    {
                        'desc': '可能感兴趣的人',
                        'card_type': 42,
                        'style': 0,
                        'title_extra_text': '查看更多',
                        'display_arrow': 1,
                        'scheme': 'https://m.weibo.cn/c/attention/visit?showmenu=0&sign=5319509655&source=Mg%3D%3D&role=NA%3D%3D&luicode=10000011&lfid=1076035319509655',
                        'actionlog': {'act_code': 695, 'cardid': '1076030001_LinkToRecomm'},
                    },
                    {
                        'card_type': 10,
                        'itemid': '1076031001_1_16.4_5319509655_7213691098_8b4bc52d',
                        'scheme': 'https://m.weibo.cn/u/7213691098?uid=7213691098&ext=growth%3A1%7Cterminal%3A%7Creason%3A16.4%7Cuid%3A5253047848%7Cbuid%3A5319509655%7Cfollow%3A7213691098%7Cact%3Askip%7Cact_valu%3Ascheme%7Cskiptype%3Aprofile%7Cagain%3A&featurecode=10000326&luicode=10000011&lfid=1076035319509655',
                        'background_color': 0,
                        'openurl': '',
                        'recom_remark': '',
                        'recommend': '',
                        'desc1': '@YINGSSssYY 的关注',
                        'desc2': '@YINGSSssYY 的关注',
                        'user': {
                            'id': 7213691098,
                            'screen_name': '胡夏全球后援官博',
                            'profile_image_url': 'https://tvax1.sinaimg.cn/crop.0.0.828.828.180/007SbUAqly8gu5gj8meywj30n00n0my6.jpg?KID=imgbed,tva&Expires=1638719372&ssig=1lJjeCBZEx',
                            'profile_url': 'https://m.weibo.cn/u/7213691098?uid=7213691098&luicode=10000011&lfid=1076035319509655',
                            'statuses_count': None,
                            'verified': True,
                            'verified_type': 7,
                            'verified_type_ext': 50,
                            'verified_reason': '胡夏官方粉丝后援会官方微博',
                            'close_blue_v': False,
                            'description': '大雨文化认证/胡夏唯一官方粉丝后援会',
                            'gender': 'm',
                            'mbtype': None,
                            'urank': None,
                            'mbrank': None,
                            'follow_me': None,
                            'following': None,
                            'follow_count': 17,
                            'followers_count': '1.3万',
                            'followers_count_str': '1.3万',
                            'cover_image_phone': 'https://tva1.sinaimg.cn/crop.0.0.640.640.640/549d0121tw1egm1kjly3jj20hs0hsq4f.jpg',
                            'avatar_hd': 'https://wx1.sinaimg.cn/orj480/007SbUAqly8gu5gj8meywj30n00n0my6.jpg',
                            'desc1': '',
                            'desc2': None,
                        },
                        'actionlog': {
                            'act_code': '1338',
                            'cardid': '1076031001_1_16.4_5319509655_7213691098_8b4bc52d',
                            'oid': '7213691098',
                            'featurecode': '10000326',
                            'mark': '',
                            'ext': 'growth:1|terminal:|reason:16.4|uid:5253047848|buid:5319509655|follow:7213691098|act:skip|act_valu:scheme|skiptype:profile|again:|pos:-1',
                            'uicode': '',
                            'luicode': '',
                            'fid': '1076035319509655',
                            'lfid': '',
                            'lcardid': '',
                        },
                        'buttons': [
                            {
                                'type': 'follow',
                                'sub_type': 0,
                                'name': '关注',
                                'skip_format': 1,
                                'params': {
                                    'uid': 7213691098,
                                    'need_follow': 1,
                                    'trend_ext': '1076031001_1_16.4_5319509655_7213691098_8b4bc52d',
                                    'trend_type': 42,
                                    'itemid': 7213691098,
                                    'allow_replenish': 1,
                                    'api_type': 'profile_guest_feed',
                                },
                                'actionlog': {
                                    'act_code': '1338',
                                    'cardid': '1076031001_1_16.4_5319509655_7213691098_8b4bc52d',
                                    'oid': '7213691098',
                                    'featurecode': '10000326',
                                    'mark': '',
                                    'ext': 'growth:1|terminal:|reason:16.4|uid:5253047848|buid:5319509655|follow:7213691098|act:follow|act_valu:follow|skiptype:|again:|pos:-1',
                                    'luicode': '',
                                    'fid': '1076035319509655',
                                    'lfid': '',
                                    'lcardid': '',
                                },
                                'scheme': '/api/container/btn?module=follow&uid=7213691098&cardid=1076031001_1_16.4_5319509655_7213691098_8b4bc52d',
                            }
                        ],
                    },
                    {
                        'card_type': 10,
                        'itemid': '1076031001_1_16.4_5319509655_1699432410_92fde156',
                        'scheme': 'https://m.weibo.cn/u/1699432410?uid=1699432410&ext=growth%3A1%7Cterminal%3A%7Creason%3A16.4%7Cuid%3A5253047848%7Cbuid%3A5319509655%7Cfollow%3A1699432410%7Cact%3Askip%7Cact_valu%3Ascheme%7Cskiptype%3Aprofile%7Cagain%3A&featurecode=10000326&luicode=10000011&lfid=1076035319509655',
                        'background_color': 0,
                        'openurl': '',
                        'recom_remark': '',
                        'recommend': '',
                        'desc1': '@YINGSSssYY 的关注',
                        'desc2': '@YINGSSssYY 的关注',
                        'user': {
                            'id': 1699432410,
                            'screen_name': '新华社',
                            'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.37.313.313.180/001R0E0aly1gm9cqfv87mj608p0ar77002.jpg?KID=imgbed,tva&Expires=1638719372&ssig=u2y7ySHxCK',
                            'profile_url': 'https://m.weibo.cn/u/1699432410?uid=1699432410&luicode=10000011&lfid=1076035319509655',
                            'statuses_count': None,
                            'verified': True,
                            'verified_type': 3,
                            'verified_type_ext': 0,
                            'verified_reason': '新华社法人微博',
                            'close_blue_v': False,
                            'description': '新华社官方微博，重大新闻权威首发平台。',
                            'gender': 'm',
                            'mbtype': None,
                            'urank': None,
                            'mbrank': None,
                            'follow_me': None,
                            'following': None,
                            'follow_count': 2985,
                            'followers_count': '1.07亿',
                            'followers_count_str': '1.07亿',
                            'cover_image_phone': 'https://tva1.sinaimg.cn/crop.0.0.640.640.640/549d0121tw1egm1kjly3jj20hs0hsq4f.jpg',
                            'avatar_hd': 'https://wx4.sinaimg.cn/orj480/001R0E0aly1gm9cqfv87mj608p0ar77002.jpg',
                            'desc1': '',
                            'desc2': None,
                        },
                        'actionlog': {
                            'act_code': '1338',
                            'cardid': '1076031001_1_16.4_5319509655_1699432410_92fde156',
                            'oid': '1699432410',
                            'featurecode': '10000326',
                            'mark': '',
                            'ext': 'growth:1|terminal:|reason:16.4|uid:5253047848|buid:5319509655|follow:1699432410|act:skip|act_valu:scheme|skiptype:profile|again:|pos:-1',
                            'uicode': '',
                            'luicode': '',
                            'fid': '1076035319509655',
                            'lfid': '',
                            'lcardid': '',
                        },
                        'buttons': [
                            {
                                'type': 'follow',
                                'sub_type': 0,
                                'name': '关注',
                                'skip_format': 1,
                                'params': {
                                    'uid': 1699432410,
                                    'need_follow': 1,
                                    'trend_ext': '1076031001_1_16.4_5319509655_1699432410_92fde156',
                                    'trend_type': 42,
                                    'itemid': 1699432410,
                                    'allow_replenish': 1,
                                    'api_type': 'profile_guest_feed',
                                },
                                'actionlog': {
                                    'act_code': '1338',
                                    'cardid': '1076031001_1_16.4_5319509655_1699432410_92fde156',
                                    'oid': '1699432410',
                                    'featurecode': '10000326',
                                    'mark': '',
                                    'ext': 'growth:1|terminal:|reason:16.4|uid:5253047848|buid:5319509655|follow:1699432410|act:follow|act_valu:follow|skiptype:|again:|pos:-1',
                                    'luicode': '',
                                    'fid': '1076035319509655',
                                    'lfid': '',
                                    'lcardid': '',
                                },
                                'scheme': '/api/container/btn?module=follow&uid=1699432410&cardid=1076031001_1_16.4_5319509655_1699432410_92fde156',
                            }
                        ],
                    },
                    {
                        'card_type': 10,
                        'itemid': '1076032001_7421553965_211203250325381464',
                        'scheme': 'https://m.weibo.cn/u/7421553965?uid=7421553965&ext=growth%3A1%7Cterminal%3A%7Creason%3A11%7Cuid%3A5253047848%7Cbuid%3A-1%7Cfollow%3A7421553965%7Cact%3Askip%7Cact_valu%3Ascheme%7Cskiptype%3Aprofile%7Cagain%3A&featurecode=10000326&luicode=10000011&lfid=1076035319509655',
                        'background_color': 0,
                        'openurl': '',
                        'recom_remark': '',
                        'recommend': '',
                        'desc1': '您可能对他感兴趣',
                        'desc2': '您可能对他感兴趣',
                        'user': {
                            'id': 7421553965,
                            'screen_name': 'grounds_official',
                            'profile_image_url': 'https://tvax2.sinaimg.cn/crop.124.114.310.310.180/0086g5djly8gd8h0g7i2fj30fi0fiwf9.jpg?KID=imgbed,tva&Expires=1638719372&ssig=NnfI1WB1wP',
                            'profile_url': 'https://m.weibo.cn/u/7421553965?uid=7421553965&luicode=10000011&lfid=1076035319509655',
                            'statuses_count': None,
                            'verified': True,
                            'verified_type': 2,
                            'verified_type_ext': 50,
                            'verified_reason': '株式会社FOOLS',
                            'close_blue_v': False,
                            'description': '来自日本的鞋履品牌，旨在重塑人与地面的沟通方式。',
                            'gender': 'm',
                            'mbtype': None,
                            'urank': None,
                            'mbrank': None,
                            'follow_me': None,
                            'following': None,
                            'follow_count': 6,
                            'followers_count': '2397',
                            'followers_count_str': '2397',
                            'cover_image_phone': 'https://tva1.sinaimg.cn/crop.0.0.640.640.640/549d0121tw1egm1kjly3jj20hs0hsq4f.jpg',
                            'avatar_hd': 'https://wx2.sinaimg.cn/orj480/0086g5djly8gd8h0g7i2fj30fi0fiwf9.jpg',
                            'desc1': '',
                            'desc2': None,
                        },
                        'actionlog': {
                            'act_code': '1338',
                            'cardid': '1076032001_7421553965_211203250325381464',
                            'oid': '7421553965',
                            'featurecode': '10000326',
                            'mark': '',
                            'ext': 'growth:1|terminal:|reason:11|uid:5253047848|buid:-1|follow:7421553965|act:skip|act_valu:scheme|skiptype:profile|again:|pos:-1',
                            'uicode': '',
                            'luicode': '',
                            'fid': '1076035319509655',
                            'lfid': '',
                            'lcardid': '',
                        },
                        'buttons': [
                            {
                                'type': 'follow',
                                'sub_type': 0,
                                'name': '关注',
                                'skip_format': 1,
                                'params': {
                                    'uid': 7421553965,
                                    'need_follow': 1,
                                    'trend_ext': '1076032001_7421553965_211203250325381464',
                                    'trend_type': 42,
                                    'itemid': 7421553965,
                                    'allow_replenish': 1,
                                    'api_type': 'profile_guest_feed',
                                },
                                'actionlog': {
                                    'act_code': '1338',
                                    'cardid': '1076032001_7421553965_211203250325381464',
                                    'oid': '7421553965',
                                    'featurecode': '10000326',
                                    'mark': '',
                                    'ext': 'growth:1|terminal:|reason:11|uid:5253047848|buid:-1|follow:7421553965|act:follow|act_valu:follow|skiptype:|again:|pos:-1',
                                    'luicode': '',
                                    'fid': '1076035319509655',
                                    'lfid': '',
                                    'lcardid': '',
                                },
                                'scheme': '/api/container/btn?module=follow&uid=7421553965&cardid=1076032001_7421553965_211203250325381464',
                            }
                        ],
                    },
                ],
            },
            {
                'card_type': 9,
                'itemid': '1076035319509655_-_4709581055855191',
                'scheme': 'https://m.weibo.cn/status/L41fjozcz?mblogid=L41fjozcz&luicode=10000011&lfid=1076035319509655',
                'mblog': {
                    'visible': {'type': 0, 'list_id': 0},
                    'created_at': 'Wed Dec 01 13:04:46 +0800 2021',
                    'id': '4709581055855191',
                    'mid': '4709581055855191',
                    'can_edit': False,
                    'version': 1,
                    'show_additional_indication': 0,
                    'text': '<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E7%8E%8B%E8%8E%89%E8%83%A1%E5%A4%8F%E5%94%B1%E7%81%AF%E7%81%AB%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%23&extparam=%23%E7%8E%8B%E8%8E%89%E8%83%A1%E5%A4%8F%E5%94%B1%E7%81%AF%E7%81%AB%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%23&luicode=10000011&lfid=1076035319509655" data-hide=""><span class="surl-text">#王莉胡夏唱灯火里的中国#</span></a> 分享视频 歌手：王莉/胡夏《灯火里的中国》 <a data-url="http://t.cn/A6xKsbhJ" href="https://c.y.qq.com/base/fcgi-bin/u?__=hxIAfKwg4JGn" data-hide=""><span class=\'url-icon\'><img style=\'width: 1rem;height: 1rem\' src=\'https://h5.sinaimg.cn/upload/2015/09/25/3/timeline_card_small_video_default.png\'></span><span class="surl-text">灯火里的中国</span></a> <a href=\'/n/QQ音乐\'>@QQ音乐</a> ',
                    'textLength': 94,
                    'source': '微博视频号',
                    'favorited': False,
                    'pic_ids': ['005O07sPgy1gwy90nfrhij30dw07umxj'],
                    'pic_types': '0',
                    'thumbnail_pic': 'https://wx3.sinaimg.cn/thumbnail/005O07sPgy1gwy90nfrhij30dw07umxj.jpg',
                    'bmiddle_pic': 'http://wx3.sinaimg.cn/bmiddle/005O07sPgy1gwy90nfrhij30dw07umxj.jpg',
                    'original_pic': 'https://wx3.sinaimg.cn/large/005O07sPgy1gwy90nfrhij30dw07umxj.jpg',
                    'is_paid': False,
                    'mblog_vip_type': 0,
                    'user': {
                        'id': 5319509655,
                        'screen_name': 'YINGSSssYY',
                        'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.0.751.751.180/005O07sPly8fxle1ardi6j30kv0kvab2.jpg?KID=imgbed,tva&Expires=1638719372&ssig=0nWfvQeIJS',
                        'profile_url': 'https://m.weibo.cn/u/5319509655?uid=5319509655&luicode=10000011&lfid=1076035319509655',
                        'statuses_count': 826,
                        'verified': True,
                        'verified_type': 0,
                        'verified_type_ext': 0,
                        'verified_reason': '微博原创视频博主',
                        'close_blue_v': False,
                        'description': 'If we can only encounter each other rather than stay with each other, then I wish we had never encountered.',
                        'gender': 'f',
                        'mbtype': 12,
                        'urank': 32,
                        'mbrank': 3,
                        'follow_me': False,
                        'following': False,
                        'follow_count': 67,
                        'followers_count': '1463',
                        'followers_count_str': '1463',
                        'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/005O07sPly1ghehzohj1kj30u00u0dim.jpg',
                        'avatar_hd': 'https://wx4.sinaimg.cn/orj480/005O07sPly8fxle1ardi6j30kv0kvab2.jpg',
                        'like': False,
                        'like_me': False,
                        'badge': {
                            'bind_taobao': 1,
                            'unread_pool': 1,
                            'unread_pool_ext': 1,
                            'dzwbqlx_2016': 1,
                            'league_badge': 1,
                            'travel_2017': 1,
                            'panda': 1,
                            'user_name_certificate': 1,
                            'hongbao_2020': 2,
                            'pc_new': 7,
                            'hongbaofeijika_2021': 1,
                            'party_cardid_state': 1,
                        },
                    },
                    'reposts_count': 0,
                    'comments_count': 0,
                    'reprint_cmt_count': 0,
                    'attitudes_count': 1,
                    'pending_approval_count': 0,
                    'isLongText': False,
                    'reward_exhibition_type': 0,
                    'hide_flag': 0,
                    'mlevel': 0,
                    'darwin_tags': [],
                    'mblogtype': 0,
                    'rid': '3_0_50_6665514537312526293_0_0_0',
                    'more_info_type': 0,
                    'cardid': 'star_033',
                    'extern_safe': 0,
                    'number_display_strategy': {
                        'apply_scenario_flag': 3,
                        'display_text_min_number': 1000000,
                        'display_text': '100万+',
                    },
                    'enable_comment_guide': True,
                    'content_auth': 0,
                    'safe_tags': 4096,
                    'pic_num': 1,
                    'alchemy_params': {'ug_red_envelope': False},
                    'reprint_type': 0,
                    'can_reprint': True,
                    'new_comment_style': 0,
                    'mblog_menu_new_style': 0,
                    'edit_config': {'edited': False},
                    'page_info': {
                        'type': 'video',
                        'object_type': 11,
                        'url_ori': 'http://t.cn/A6xKsbhJ',
                        'page_pic': {
                            'width': 640,
                            'url': 'http://y.gtimg.cn/music/photo_new/T015R640x360M101002L7PYz2FEMn5.jpg',
                            'height': 360,
                        },
                        'page_url': 'https://weibo.cn/sinaurl?ADTAG=cbshare&appshare=android_qq&appversion=11000106&channelId=10036163&hosteuin=owEkNKSi7ioion%2A%2A&openinqqmusic=1&platform=11&vid=y0041be8gvx&luicode=10000011&lfid=1076035319509655&u=https%3A%2F%2Fi.y.qq.com%2Fn2%2Fm%2Fshare%2Fdetails%2Fmv.html%3FADTAG%3Dcbshare%26appshare%3Dandroid_qq%26appversion%3D11000106%26channelId%3D10036163%26hosteuin%3DowEkNKSi7ioion%252A%252A%26openinqqmusic%3D1%26platform%3D11%26vid%3Dy0041be8gvx',
                        'object_id': '1042198:y0041be8gvx',
                        'page_title': '灯火里的中国',
                        'title': '灯火里的中国',
                        'content1': '灯火里的中国',
                        'content2': '',
                        'video_orientation': None,
                        'play_count': '493次播放',
                        'media_info': {
                            'stream_url': 'https://c.y.qq.com/base/fcgi-bin/fcg_pyq_mv.fcg?vid=y0041be8gvx&type=low&code=d3f64&tag=61a79114',
                            'stream_url_hd': 'https://c.y.qq.com/base/fcgi-bin/fcg_pyq_mv.fcg?vid=y0041be8gvx&type=hd&code=1e077&tag=61a79114',
                            'duration': '261',
                        },
                        'urls': None,
                    },
                    'pics': [
                        {
                            'pid': '005O07sPgy1gwy90nfrhij30dw07umxj',
                            'url': 'https://wx3.sinaimg.cn/orj360/005O07sPgy1gwy90nfrhij30dw07umxj.jpg',
                            'size': 'orj360',
                            'geo': {'width': 478, 'height': 270, 'croped': False},
                            'large': {
                                'size': 'large',
                                'url': 'https://wx3.sinaimg.cn/large/005O07sPgy1gwy90nfrhij30dw07umxj.jpg',
                                'geo': {'width': '500', 'height': '282', 'croped': False},
                            },
                        }
                    ],
                    'bid': 'L41fjozcz',
                },
            },
            {
                'card_type': 9,
                'itemid': '1076035319509655_-_4709580799476041',
                'scheme': 'https://m.weibo.cn/status/L41eTDL9n?mblogid=L41eTDL9n&luicode=10000011&lfid=1076035319509655',
                'mblog': {
                    'visible': {'type': 0, 'list_id': 0},
                    'created_at': 'Wed Dec 01 13:03:44 +0800 2021',
                    'id': '4709580799476041',
                    'mid': '4709580799476041',
                    'can_edit': False,
                    'version': 1,
                    'show_additional_indication': 0,
                    'text': '王莉/胡夏《灯火里的中国》<a data-url="http://t.cn/A6xKFeGc" href="http://t.cn/A6xKFeGc" data-hide=""><span class=\'url-icon\'><img style=\'width: 1rem;height: 1rem\' src=\'https://h5.sinaimg.cn/upload/2015/09/25/3/timeline_card_small_web_default.png\'></span><span class="surl-text">灯火里的中国</span></a> <a href=\'/n/QQ音乐\'>@QQ音乐</a> ',
                    'textLength': 53,
                    'source': '',
                    'favorited': False,
                    'pic_ids': [],
                    'pic_types': '',
                    'is_paid': False,
                    'mblog_vip_type': 0,
                    'user': {
                        'id': 5319509655,
                        'screen_name': 'YINGSSssYY',
                        'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.0.751.751.180/005O07sPly8fxle1ardi6j30kv0kvab2.jpg?KID=imgbed,tva&Expires=1638719372&ssig=0nWfvQeIJS',
                        'profile_url': 'https://m.weibo.cn/u/5319509655?uid=5319509655&luicode=10000011&lfid=1076035319509655',
                        'statuses_count': 826,
                        'verified': True,
                        'verified_type': 0,
                        'verified_type_ext': 0,
                        'verified_reason': '微博原创视频博主',
                        'close_blue_v': False,
                        'description': 'If we can only encounter each other rather than stay with each other, then I wish we had never encountered.',
                        'gender': 'f',
                        'mbtype': 12,
                        'urank': 32,
                        'mbrank': 3,
                        'follow_me': False,
                        'following': False,
                        'follow_count': 67,
                        'followers_count': '1463',
                        'followers_count_str': '1463',
                        'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/005O07sPly1ghehzohj1kj30u00u0dim.jpg',
                        'avatar_hd': 'https://wx4.sinaimg.cn/orj480/005O07sPly8fxle1ardi6j30kv0kvab2.jpg',
                        'like': False,
                        'like_me': False,
                        'badge': {
                            'bind_taobao': 1,
                            'unread_pool': 1,
                            'unread_pool_ext': 1,
                            'dzwbqlx_2016': 1,
                            'league_badge': 1,
                            'travel_2017': 1,
                            'panda': 1,
                            'user_name_certificate': 1,
                            'hongbao_2020': 2,
                            'pc_new': 7,
                            'hongbaofeijika_2021': 1,
                            'party_cardid_state': 1,
                        },
                    },
                    'reposts_count': 1,
                    'comments_count': 1,
                    'reprint_cmt_count': 0,
                    'attitudes_count': 2,
                    'pending_approval_count': 0,
                    'isLongText': False,
                    'reward_exhibition_type': 0,
                    'hide_flag': 0,
                    'mlevel': 0,
                    'darwin_tags': [],
                    'mblogtype': 0,
                    'rid': '4_0_50_6665514537312526293_0_0_0',
                    'more_info_type': 0,
                    'cardid': 'star_033',
                    'extern_safe': 0,
                    'number_display_strategy': {
                        'apply_scenario_flag': 3,
                        'display_text_min_number': 1000000,
                        'display_text': '100万+',
                    },
                    'enable_comment_guide': True,
                    'content_auth': 0,
                    'safe_tags': 32,
                    'pic_num': 0,
                    'alchemy_params': {'ug_red_envelope': False},
                    'reprint_type': 0,
                    'can_reprint': False,
                    'new_comment_style': 0,
                    'mblog_menu_new_style': 0,
                    'edit_config': {'edited': False},
                    'page_info': {
                        'object_type': 2,
                        'type': 'webpage',
                        'page_pic': {
                            'width': 300,
                            'url': 'https://y.gtimg.cn/music/photo_new/T002R300x300M000001hQ5RR4dGKAr.jpg',
                            'height': 300,
                        },
                        'page_url': 'https://weibo.cn/sinaurl?ADTAG=swbshare&_wv=1&appshare=iphone&appsongtype=1&channelId=10036163&hosteuin=oKosNKo5NecA7z%2A%2A&media_mid=000han5K35o7UE&openinqqmusic=1&platform=1&songid=334848276&songmid=&source=qq&type=0&luicode=10000011&lfid=1076035319509655&u=https%3A%2F%2Fi.y.qq.com%2Fv8%2Fplaysong.html%3FADTAG%3Dswbshare%26_wv%3D1%26appshare%3Diphone%26appsongtype%3D1%26channelId%3D10036163%26hosteuin%3DoKosNKo5NecA7z%252A%252A%26media_mid%3D000han5K35o7UE%26openinqqmusic%3D1%26platform%3D1%26songid%3D334848276%26songmid%3D%26source%3Dqq%26type%3D0',
                        'url_ori': 'http://t.cn/A6xKFeGc',
                        'page_title': '王莉',
                        'content1': '',
                    },
                    'bid': 'L41eTDL9n',
                },
            },
            {'card_type': 11, 'show_type': 0, 'card_group': []},
            {
                'card_type': 9,
                'itemid': '1076035319509655_-_4708563794003411',
                'scheme': 'https://m.weibo.cn/status/L3AMzgNt9?mblogid=L3AMzgNt9&luicode=10000011&lfid=1076035319509655',
                'mblog': {
                    'visible': {'type': 0, 'list_id': 0},
                    'created_at': 'Sun Nov 28 17:42:32 +0800 2021',
                    'id': '4708563794003411',
                    'mid': '4708563794003411',
                    'can_edit': False,
                    'show_additional_indication': 0,
                    'text': '我从不信什么知错就改，我只知道狗改不了吃屎。 ',
                    'textLength': 44,
                    'source': '微博国际版',
                    'favorited': False,
                    'pic_ids': [],
                    'pic_types': '',
                    'is_paid': False,
                    'mblog_vip_type': 0,
                    'user': {
                        'id': 5319509655,
                        'screen_name': 'YINGSSssYY',
                        'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.0.751.751.180/005O07sPly8fxle1ardi6j30kv0kvab2.jpg?KID=imgbed,tva&Expires=1638719372&ssig=0nWfvQeIJS',
                        'profile_url': 'https://m.weibo.cn/u/5319509655?uid=5319509655&luicode=10000011&lfid=1076035319509655',
                        'statuses_count': 826,
                        'verified': True,
                        'verified_type': 0,
                        'verified_type_ext': 0,
                        'verified_reason': '微博原创视频博主',
                        'close_blue_v': False,
                        'description': 'If we can only encounter each other rather than stay with each other, then I wish we had never encountered.',
                        'gender': 'f',
                        'mbtype': 12,
                        'urank': 32,
                        'mbrank': 3,
                        'follow_me': False,
                        'following': False,
                        'follow_count': 67,
                        'followers_count': '1463',
                        'followers_count_str': '1463',
                        'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/005O07sPly1ghehzohj1kj30u00u0dim.jpg',
                        'avatar_hd': 'https://wx4.sinaimg.cn/orj480/005O07sPly8fxle1ardi6j30kv0kvab2.jpg',
                        'like': False,
                        'like_me': False,
                        'badge': {
                            'bind_taobao': 1,
                            'unread_pool': 1,
                            'unread_pool_ext': 1,
                            'dzwbqlx_2016': 1,
                            'league_badge': 1,
                            'travel_2017': 1,
                            'panda': 1,
                            'user_name_certificate': 1,
                            'hongbao_2020': 2,
                            'pc_new': 7,
                            'hongbaofeijika_2021': 1,
                            'party_cardid_state': 1,
                        },
                    },
                    'reposts_count': 0,
                    'comments_count': 0,
                    'reprint_cmt_count': 0,
                    'attitudes_count': 1,
                    'pending_approval_count': 0,
                    'isLongText': False,
                    'reward_exhibition_type': 0,
                    'hide_flag': 0,
                    'mlevel': 0,
                    'darwin_tags': [],
                    'mblogtype': 0,
                    'rid': '6_0_50_6665514537312526293_0_0_0',
                    'more_info_type': 0,
                    'cardid': 'star_033',
                    'extern_safe': 0,
                    'number_display_strategy': {
                        'apply_scenario_flag': 3,
                        'display_text_min_number': 1000000,
                        'display_text': '100万+',
                    },
                    'enable_comment_guide': True,
                    'content_auth': 0,
                    'pic_num': 0,
                    'alchemy_params': {'ug_red_envelope': False},
                    'reprint_type': 0,
                    'can_reprint': False,
                    'new_comment_style': 0,
                    'mblog_menu_new_style': 0,
                    'edit_config': {'edited': False},
                    'bid': 'L3AMzgNt9',
                },
            },
            {
                'card_type': 9,
                'itemid': '1076035319509655_-_4707000024566483',
                'scheme': 'https://m.weibo.cn/status/L2W6mj9WX?mblogid=L2W6mj9WX&luicode=10000011&lfid=1076035319509655',
                'mblog': {
                    'visible': {'type': 0, 'list_id': 0},
                    'created_at': 'Wed Nov 24 10:08:40 +0800 2021',
                    'id': '4707000024566483',
                    'mid': '4707000024566483',
                    'can_edit': False,
                    'version': 1,
                    'show_additional_indication': 0,
                    'text': '胡夏《半暖时光》（《半暖时光》电视剧主题曲）<a data-url="http://t.cn/A6xivFJS" href="http://t.cn/A6xivFJS" data-hide=""><span class=\'url-icon\'><img style=\'width: 1rem;height: 1rem\' src=\'https://h5.sinaimg.cn/upload/2015/09/25/3/timeline_card_small_web_default.png\'></span><span class="surl-text">半暖时光</span></a> <a href=\'/n/QQ音乐\'>@QQ音乐</a> ',
                    'textLength': 72,
                    'source': '',
                    'favorited': False,
                    'pic_ids': [],
                    'pic_types': '',
                    'is_paid': False,
                    'mblog_vip_type': 0,
                    'user': {
                        'id': 5319509655,
                        'screen_name': 'YINGSSssYY',
                        'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.0.751.751.180/005O07sPly8fxle1ardi6j30kv0kvab2.jpg?KID=imgbed,tva&Expires=1638719372&ssig=0nWfvQeIJS',
                        'profile_url': 'https://m.weibo.cn/u/5319509655?uid=5319509655&luicode=10000011&lfid=1076035319509655',
                        'statuses_count': 826,
                        'verified': True,
                        'verified_type': 0,
                        'verified_type_ext': 0,
                        'verified_reason': '微博原创视频博主',
                        'close_blue_v': False,
                        'description': 'If we can only encounter each other rather than stay with each other, then I wish we had never encountered.',
                        'gender': 'f',
                        'mbtype': 12,
                        'urank': 32,
                        'mbrank': 3,
                        'follow_me': False,
                        'following': False,
                        'follow_count': 67,
                        'followers_count': '1463',
                        'followers_count_str': '1463',
                        'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/005O07sPly1ghehzohj1kj30u00u0dim.jpg',
                        'avatar_hd': 'https://wx4.sinaimg.cn/orj480/005O07sPly8fxle1ardi6j30kv0kvab2.jpg',
                        'like': False,
                        'like_me': False,
                        'badge': {
                            'bind_taobao': 1,
                            'unread_pool': 1,
                            'unread_pool_ext': 1,
                            'dzwbqlx_2016': 1,
                            'league_badge': 1,
                            'travel_2017': 1,
                            'panda': 1,
                            'user_name_certificate': 1,
                            'hongbao_2020': 2,
                            'pc_new': 7,
                            'hongbaofeijika_2021': 1,
                            'party_cardid_state': 1,
                        },
                    },
                    'reposts_count': 0,
                    'comments_count': 0,
                    'reprint_cmt_count': 0,
                    'attitudes_count': 1,
                    'pending_approval_count': 0,
                    'isLongText': False,
                    'reward_exhibition_type': 0,
                    'hide_flag': 0,
                    'mlevel': 0,
                    'darwin_tags': [],
                    'mblogtype': 0,
                    'rid': '7_0_50_6665514537312526293_0_0_0',
                    'more_info_type': 0,
                    'cardid': 'star_033',
                    'extern_safe': 0,
                    'number_display_strategy': {
                        'apply_scenario_flag': 3,
                        'display_text_min_number': 1000000,
                        'display_text': '100万+',
                    },
                    'enable_comment_guide': True,
                    'content_auth': 0,
                    'safe_tags': 32,
                    'pic_num': 0,
                    'alchemy_params': {'ug_red_envelope': False},
                    'reprint_type': 0,
                    'can_reprint': False,
                    'new_comment_style': 0,
                    'mblog_menu_new_style': 0,
                    'edit_config': {'edited': False},
                    'page_info': {
                        'object_type': 2,
                        'type': 'webpage',
                        'page_pic': {
                            'width': 300,
                            'url': 'https://y.gtimg.cn/music/photo_new/T002R300x300M000000KUI752FTEW6.jpg',
                            'height': 300,
                        },
                        'page_url': 'https://weibo.cn/sinaurl?ADTAG=swbshare&_wv=1&appshare=iphone&appsongtype=1&channelId=10036163&hosteuin=oKosNKo5NecA7z%2A%2A&media_mid=003GtYDo36TE3l&openinqqmusic=1&platform=1&songid=333500096&songmid=&source=qq&type=0&luicode=10000011&lfid=1076035319509655&u=https%3A%2F%2Fi.y.qq.com%2Fv8%2Fplaysong.html%3FADTAG%3Dswbshare%26_wv%3D1%26appshare%3Diphone%26appsongtype%3D1%26channelId%3D10036163%26hosteuin%3DoKosNKo5NecA7z%252A%252A%26media_mid%3D003GtYDo36TE3l%26openinqqmusic%3D1%26platform%3D1%26songid%3D333500096%26songmid%3D%26source%3Dqq%26type%3D0',
                        'url_ori': 'http://t.cn/A6xivFJS',
                        'page_title': '胡夏',
                        'content1': '',
                    },
                    'bid': 'L2W6mj9WX',
                },
            },
            {
                'card_type': 9,
                'itemid': '1076035319509655_-_4706671580942170',
                'scheme': 'https://m.weibo.cn/status/L2NyC3X6i?mblogid=L2NyC3X6i&luicode=10000011&lfid=1076035319509655',
                'mblog': {
                    'visible': {'type': 0, 'list_id': 0},
                    'created_at': 'Tue Nov 23 12:23:33 +0800 2021',
                    'id': '4706671580942170',
                    'mid': '4706671580942170',
                    'can_edit': False,
                    'version': 1,
                    'show_additional_indication': 0,
                    'text': '林子祥/胡夏《选择 (Live)》<a data-url="http://t.cn/A6xJAuwk" href="http://t.cn/A6xJAuwk" data-hide=""><span class=\'url-icon\'><img style=\'width: 1rem;height: 1rem\' src=\'https://h5.sinaimg.cn/upload/2015/09/25/3/timeline_card_small_web_default.png\'></span><span class="surl-text">选择</span></a> <a href=\'/n/QQ音乐\'>@QQ音乐</a> ',
                    'textLength': 54,
                    'source': '',
                    'favorited': False,
                    'pic_ids': [],
                    'pic_types': '',
                    'is_paid': False,
                    'mblog_vip_type': 0,
                    'user': {
                        'id': 5319509655,
                        'screen_name': 'YINGSSssYY',
                        'profile_image_url': 'https://tvax4.sinaimg.cn/crop.0.0.751.751.180/005O07sPly8fxle1ardi6j30kv0kvab2.jpg?KID=imgbed,tva&Expires=1638719372&ssig=0nWfvQeIJS',
                        'profile_url': 'https://m.weibo.cn/u/5319509655?uid=5319509655&luicode=10000011&lfid=1076035319509655',
                        'statuses_count': 826,
                        'verified': True,
                        'verified_type': 0,
                        'verified_type_ext': 0,
                        'verified_reason': '微博原创视频博主',
                        'close_blue_v': False,
                        'description': 'If we can only encounter each other rather than stay with each other, then I wish we had never encountered.',
                        'gender': 'f',
                        'mbtype': 12,
                        'urank': 32,
                        'mbrank': 3,
                        'follow_me': False,
                        'following': False,
                        'follow_count': 67,
                        'followers_count': '1463',
                        'followers_count_str': '1463',
                        'cover_image_phone': 'https://wx2.sinaimg.cn/crop.0.0.640.640.640/005O07sPly1ghehzohj1kj30u00u0dim.jpg',
                        'avatar_hd': 'https://wx4.sinaimg.cn/orj480/005O07sPly8fxle1ardi6j30kv0kvab2.jpg',
                        'like': False,
                        'like_me': False,
                        'badge': {
                            'bind_taobao': 1,
                            'unread_pool': 1,
                            'unread_pool_ext': 1,
                            'dzwbqlx_2016': 1,
                            'league_badge': 1,
                            'travel_2017': 1,
                            'panda': 1,
                            'user_name_certificate': 1,
                            'hongbao_2020': 2,
                            'pc_new': 7,
                            'hongbaofeijika_2021': 1,
                            'party_cardid_state': 1,
                        },
                    },
                    'reposts_count': 0,
                    'comments_count': 0,
                    'reprint_cmt_count': 0,
                    'attitudes_count': 2,
                    'pending_approval_count': 0,
                    'isLongText': False,
                    'reward_exhibition_type': 0,
                    'hide_flag': 0,
                    'mlevel': 0,
                    'darwin_tags': [],
                    'mblogtype': 0,
                    'rid': '8_0_50_6665514537312526293_0_0_0',
                    'more_info_type': 0,
                    'cardid': 'star_033',
                    'extern_safe': 0,
                    'number_display_strategy': {
                        'apply_scenario_flag': 3,
                        'display_text_min_number': 1000000,
                        'display_text': '100万+',
                    },
                    'enable_comment_guide': True,
                    'content_auth': 0,
                    'safe_tags': 32,
                    'pic_num': 0,
                    'alchemy_params': {'ug_red_envelope': False},
                    'reprint_type': 0,
                    'can_reprint': False,
                    'new_comment_style': 0,
                    'mblog_menu_new_style': 0,
                    'edit_config': {'edited': False},
                    'page_info': {
                        'object_type': 2,
                        'type': 'webpage',
                        'page_pic': {
                            'width': 300,
                            'url': 'https://y.gtimg.cn/music/photo_new/T002R300x300M00000158yZI3TQsPC.jpg',
                            'height': 300,
                        },
                        'page_url': 'https://weibo.cn/sinaurl?ADTAG=swbshare&_wv=1&appshare=iphone&appsongtype=1&channelId=10036163&hosteuin=oKosNKo5NecA7z%2A%2A&media_mid=001iCo0N30TafW&openinqqmusic=1&platform=1&songid=333430506&songmid=&source=qq&type=0&luicode=10000011&lfid=1076035319509655&u=https%3A%2F%2Fi.y.qq.com%2Fv8%2Fplaysong.html%3FADTAG%3Dswbshare%26_wv%3D1%26appshare%3Diphone%26appsongtype%3D1%26channelId%3D10036163%26hosteuin%3DoKosNKo5NecA7z%252A%252A%26media_mid%3D001iCo0N30TafW%26openinqqmusic%3D1%26platform%3D1%26songid%3D333430506%26songmid%3D%26source%3Dqq%26type%3D0',
                        'url_ori': 'http://t.cn/A6xJAuwk',
                        'page_title': '林子祥',
                        'content1': '',
                    },
                    'bid': 'L2NyC3X6i',
                },
            },
        ],
        'scheme': 'sinaweibo://cardlist?containerid=1076035319509655&uid=5319509655&t=0&luicode=10000011&lfid=100103type%3D1%26q%3D%E5%9B%9B%E5%B7%9D%E6%97%A5%E6%8A%A5&type=uid&value=5319509655&page=1&oid=4706307662153913&v_p=42',
        'showAppTips': 0,
    }
